all: 
	mkdir -p bin
	g++ -std=c++0x -Wall -Werror -ansi -pedantic main.cpp tokenClass.cpp -o /bin/rshell.out

rshell:
	mkdir -p bin
	g++ -std=c++0x -Wall -Werror -ansi -pedantic main.cpp tokenClass.cpp -o /bin/rshell.out
